services:
  strudel:
    container_name: strudel
    image: ghcr.io/the-alphabet-cartel/strudel-docker:latest
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - strudel-network

  nginx:
    container_name: strudel-proxy
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - strudel-network
    depends_on:
      - strudel
      
networks:
  strudel-network:
    driver: bridge
