services:
  strudel:
    container_name: strudel
    image: ghcr.io/the-alphabet-cartel/strudel-docker:latest
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - strudel-network

networks:
  strudel-network:
    driver: bridge
